from a2a.core.message import AgentMessage


class BaseMessageQueue:
    async def send(self, message: AgentMessage): ...
    async def receive(self, agent_id: str) -> AgentMessage: ...
    async def broadcast(self, message: AgentMessage): ...
